### ISSUE TITLE
Mulighed for at vælge spørgsmål baseret på ét (eller flere?) søgeord

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#132]
Hvis det ikke ønskes (fordi det måske er for besværligt for en "almen bruger"), så kunne jeg i hvert fald godt tænke det til mig selv (eller superbrugere).

**Comment by morsby** [comment]
Jeg tænker, det er en fin idé - men spændt på, hvor "gode" søgeordene er nødt til at være for at få et ordentligt antal resultater.

**Comment by thomasjensen1194** [comment]
Samme her! Skal nok vende tilbage med feedback!
