### ISSUE TITLE
Klargøring af client til server-flytning

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#161]
Hvad end der nu ligger i ./secretkeys skal flyttes ind i en environmental variable (håber det kan lade sig gøre??). Det er ikke særligt sikkert at have secrets i en fil, som vi importerer. Derudover så kan vi ikke deploy automatisk hvis den fil skal eksistere.

Derudover skal  AU's environmental variable ændres, og samme variable i prod.js fra MONGO_URI til MONGO_URL
Dette kræver Dokku, og det er nemmest hvis vi har samme setup på begge servere, indtil vi får alt flyttet

**Comment by morsby** [comment]
- [x] Secrets flyttet environment variable (`/prod.js`)
- [x] Omdøbt MONGO_URI til `MONGO_URL` på server og `/prod.js`
