### ISSUE TITLE
Upload af billeder til kommentarer

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#169]

**Comment by morsby** [comment]
Er det ikke lidt overkill? Plus - copyright. Tror ikke den der "til undervisningsbrug" holder, når det ikke er fra AUs hånd?

**Comment by morsby** [comment]
... jeg er med på, der sagtens kan uploades andet. Men vi kan ikke filtrere copyrights fra, og så vil jeg hellere bare have at folk linker/henviser.

**Comment by thomasjensen1194** [comment]
Det er en god pointe, men er det ikke anderledes når brugere uploader? Kan vi blive stillet til regnskab for det?

**Comment by morsby** [comment]
Njae, nok ikke (den nye EU lov gælder vist kun for store firmaer) . Men stadig, synes det er lidt iffy.

**Comment by thomasjensen1194** [comment]
Der er i hvert fald tidspunkter hvor jeg godt kunne have haft brug for at uploade et screenshot i en kommentar. Men måske det kommer med de der Rich-text-editors?

**Comment by thomasjensen1194** [comment]
Muligt med markdown.
