### ISSUE TITLE
Quiz deling

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#172]
Godt til læsegrupper, der laver medmcq sammen:
Hver quiz skal have et ID, som man kan tilgå på forsiden, efter man har oprettet quizzen.
Det skal nok integreres i databasen, så måske i forbindelse med omskrivningen til SQL, kan man lige have det med? Bare et quiz-id column, et question-column og et "nummer i quizzen"-column, hvor man så bare kan hente alle spørgsmål med det ID man har fundet, og rangere det efter "nummer i quizzen"-column.
Kan det lade sig gøre @morsby, eller tænker du en bedre løsning findes?

**Comment by morsby** [comment]
Altså jeg ser to muligheder (forstår dog ikke helt din plan - så måske 3?).

**1. Opret en Quiz-tabel i databasen**

- Koncept: Hver gang man beder om en quiz (udover eksamenssæt [der kører via en separat API route]), gemmer vi en kopi af quizzen i databasen med referencer til de spørgsmål, der er valgt. Så kan vi senere hente alle spørgsmål, der hører til hver quiz. 
- Fordele: Det bliver elegant at sortere spørgsmål i den rigtige rækkefølge. Det kan jo samtidig fungere som en form for log af, hvad folk beder om.
- Ulemper: Det vil "unødigt" gemme langt de fleste quizzer, som formentlig laves alene - men vi har vel plads nok på serveren. Det vil også marginalt forsinke "start-quiz" processen.

**2. Klar det via front-end**

- Koncept: Redux state indeholder jo alle de spørgsmål, en bruger får. Vi kunne også bare lave en front-end implementering med "Start quiz -> del quiz", der genererer et link med alle spørgsmåls-id'er, der er i den aktuelle quiz.
- Fordele: Kræver ikke en ny database-tabel.
- Ulemper: Kan ikke fungere som log. Bliver nok mindre elegant at sortere rigtigt.

**Begge metoder** vil kræve en frontend route, der

1. henter spørgsmål fra API'en ud fra quiz-id eller liste af spørgsmåls-id'er
2. viderestiller til quiz-siden.

**Comment by thomasjensen1194** [comment]
Jeg synes 2 lyder godt, man kunne jo eventuelt på backend lave det sådan, at alle requests sendes tilbage med et ekstra key i objektet der hedder "nummer i quizzen", som frontend eventuelt ikke bruger (medmindre vi får brug for det af anden årsag). Når man så deler, så smider vi det tal med op, og så kan man hente ID'et.
Og vi kan jo sagtens stadig logge requests med et middleware (på alle routes).

Hvis du synes det er mere elegant med 1, er jeg ikke imod det - men det er måske bare unødigt meget information at lagre?

**Comment by morsby** [comment]
Jaa, 1. er måske lidt overkill.

Tænker ikke, API'en skal smide "nummer i quizzen" med - det må vi kunne klare på frontend.

**Comment by thomasjensen1194** [comment]
Jeg tror ikke det gør nogen forskel om det er frontend eller backend der smider nummeret, så vi gør bare hvad der virker bedst i implementeringen.
Synes du vi skal vente til SQL med at lave det?

**Comment by morsby** [comment]
Altså hvis det bare er frontend burde det da være overskueligt nok. Men jeg har ikke tid foreløbig.

**Comment by thomasjensen1194** [comment]
Jeg laver det gerne, så skal du bare lige sørge for at der kommer en route jeg kan poste en "delt quiz" til i SQL-integreringen.

**Comment by morsby** [comment]
Det burde ikke være nødvendigt med en speciel API - den skal jo bare hente spørgsmål ud fra en række ID'er.

MEN! Vi får et problem på windows-maskinen, fordi url'en vil blive for lang (24 tegn per id, 80 spørgsmål = 1920 tegn + kommaer mv.). Den har en grænse omkring de 2.000 tegn. Jeg kan prøve at se, om jeg kan øge grænsen senere.

**Comment by thomasjensen1194** [comment]
Ej, det er også et ALT for langt link at sende til en læsegruppe. Jeg synes vi skal lave det som et post og get - vi kan bare cleare den database en gang om måneden eksempelvis, hvis den bliver oversvømmet.

**Comment by morsby** [comment]
Det bliver jo bedre på SQL - der er id's 1-4 tegn (indtil vi når ≥ 10.000 spørgsmål).

Men ja, det andet er også en mulighed.

**Comment by thomasjensen1194** [comment]
Jeg kigger på det, men jeg tror jeg laver et POST og GET (synes jeg virker mest elegant og overskueligt).

**Comment by thomasjensen1194** [comment]
Senere kan det måske også bruges, hvis man vil gemme en quiz til senere brug (måske i undervisningen?)

**Comment by thomasjensen1194** [comment]
Er blevet integreret
