### ISSUE TITLE
Mangel på _id ved når der nogengange postes comments. Kræver clearing af website data + login igen.

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#226]
Trækker vi brugerdata både ud af redux (altså egentlig localstorage) og cookies? Fordi jeg oplever en ret stor fejl af og til, hvor man kan være logget ind, men appen smider at den ikke kan finde _id, når man kommenterer.

**Comment by morsby** [comment]
Tror jeg har fikset det her allerede - tjekker for login hvert minut.

**Comment by thomasjensen1194** [comment]
Haha ja, det smadrede også kommentarfeltet, da det blev clearet ved brugerskifte. Men har fikset det.

**Comment by morsby** [comment]
Tror dette må være fikset - i SQL lader vi være med at persist'e brugeren til localStorage.
