### ISSUE TITLE
Implementering af tracking der ikke benytter servere udefra.

### ISSUE THREAD

**Issue by thjendk** [morsby/medmcq#23]

**Comment by morsby** [comment]
Er for så vidt ikke nødvendigvis et vildt stort projekt - jeg er glad for Matomo (tidl. Piwik). Det understøtter bare kun en SQL-database - så hvis vi kunne køre sådan en ved siden af (lidt spild af ressourcer måske), er det løst.

**Comment by thjendk** [comment]
Done, og alt data migreret. Tak for hjælpen Morsby!
