### ISSUE TITLE
Kommentar slettet ved serverfejl

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#240]
Når AU's server hænger, så slettes kommentaren fra tekstfeltet, og brugeren skal til at skrive det igen, for så at håbe på, at serveren er tilbage. Vi skal have en form for loading eller throw en error ved fejloprettelse af comment

**Comment by morsby** [comment]
Kommer med sql redux refactor.

**Comment by thomasjensen1194** [comment]
Jeg har lavet en makeshift løsning i commit 5b1a1fc5c558c582e43d346a331a2a5dd36a5914
