### ISSUE TITLE
Jeg tror ikke besvarelse af spørgsmål gemmes korrekt?

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#261]
![image](https://user-images.githubusercontent.com/44089656/58463793-ce3e9080-8134-11e9-8dac-f4a3466fd26e.png)
Jeg har tidligere svaret på dette spørgsmål, men der står "svaret rigtigt 0 ud af 1 gang", og spørgsmålet optræder i quizzen selvom jeg har valgt ikke at ville have spørgsmål, jeg allerede har svaret på. Hmmm

**Comment by morsby** [comment]
Det er ikke bare et gengangerspørgsmål?

Det virker jo. Alternativt er udfald af enkelte api kald.

**Comment by morsby** [comment]
Jeg kan se, at I har kommenteret præcis det samme som "tjo" - hvor det er det eneste spørgsmål, I har svaret på med den bruger. Kan det være det?

Ellers vil jeg tro, det må have været et udfald i API'en, da det request, der registrerer svaret, gik.

Jeg har testet med at køre to sæt igennem, og alle svar blev gemt der. Tror ikke det er noget, vi kan gøre noget ved i hvert fald - uden evt. at lave noget med at retry'e requests ved fejl.

**Comment by thomasjensen1194** [comment]
Fint, vi laver et fiks for udfald på alle routes på den nye remaster (retry nogle gange). Tak fordi du gad tjekke!
