### ISSUE TITLE
Retry på alle API routes

### ISSUE THREAD

**Issue by thjendk** [morsby/medmcq#266]
Hvis requsten failer skal der ventes lidt, og så prøves igen

**Comment by thomasjensen1194** [comment]
Hvordan ser det ud med det her @morsby? Der var eksempelvis lidt problemer, hvis man skrev en kommentar, hvor der var lidt knas med AU's servere. Jeg kan se der stadig er en TODO i QuestionComment.js. Eventuelt skal der laves en midlertidig løsning, fordi det er MEGA træls når det sker.
![image](https://user-images.githubusercontent.com/44089656/62216075-66acf780-b3a8-11e9-9b8b-9c7979f9c9a7.png)

**Comment by thomasjensen1194** [comment]
Jeg har lavet en løsning i commit 5b1a1fc5c558c582e43d346a331a2a5dd36a5914

**Comment by thomasjensen1194** [comment]
Integrationen af apollo-graphql bruger en class kaldet Apollo. I denne kan der integreres retry efter nogle sekunder.
