### ISSUE TITLE
Et mindre admin-interface (ændring af spørgsmål m.v.)? Ikke full-blown, det vil blive for meget.

### ISSUE THREAD

**Issue by thjendk** [morsby/medmcq#29]

**Comment by morsby** [comment]
Jeg indbygger CRUD for alting i API'en, så API'en er klar på det. Så det bliver væsentligst en front-end ting.

**Comment by morsby** [comment]
Jeg foreslår følgende muligheder:

- import af spørgsmål
- redigering af spørgsmål
- håndtering af brugere (fx ved glemt kodeord + ingen mail el. lign.)

**Comment by thomasjensen1194** [comment]
Derudover:
- Redigering af tags
- Tilføjelse af tags
