### ISSUE TITLE
Ny implementerede eksamnsæt tjek

### ISSUE THREAD

**Issue by ALangeland** [morsby/medmcq#290]
Det nye implementerede tjek siger også man har gennemført sættet selvom opgaverne er lavet igennem tags/specialer. 

Jeg har kun lavet de første 2 sæt, men med den nye opdatering er de alle blevet checked :)
Jeg ved ikke om det virker efter hensigten eller er en fejl i systemet så ville lige give jer en melding.

**Comment by morsby** [comment]
Jeg har egentlig altid tænkt, at sættene skulle markeres som gennemført, hvis man har svaret på alle spørgsmål i sættet - uanset om man har gjort det via et fuldt sæt, tilfældige spørgsmål eller specialer/tags.

Det giver mest mening for mig - men det er måske bare mig?

**Comment by ALangeland** [comment]
Det giver egentlig meget god mening begge veje. 
Vi har bare at lave spørgsmål efter speciale og derefter lave sæt op til eksamen hvor det kan skabe en minimal forvirring, men den anden løsning giver et bedre overblik.

**Comment by morsby** [comment]
Ah, ja, det kan jeg godt se.

Som systemet er nu, holder det udelukkende styr på besvarede spørgsmål (hvert spørgsmål har et ID, og vi registrerer så at brugeren har besvaret det ID). Systemet tjekker så, om alle spørgsmål der hører til et givet sæt er besvaret - og i så fald sætter det et flueben.

At kunne adskille sæt-besvarelser fra øvrige besvarelser er lidt besværligt - det vil kræve, at vi begynder at holde styr på, at bruger X har startet eksamenssæt Y -- og KUN hvis alle spørgsmål bliver besvaret (i samme ombæring måske endda?) registrere sættet som fuldført. 

Vil det være en acceptabel middelvej, at man som bruger kan markere manuelt, hvilke sæt man har besvaret? For jeg kan godt følge dig i (og huske min egen frustration over), at det er svært at huske, hvor langt man er nået i sæt-listen.

**Comment by ALangeland** [comment]
En manuel anmærkning vil helt sikkert være en fin løsning og betydeligt nemmere at implementere.

**Comment by ALangeland** [comment]
Muligheden for manuelt at gemme bestemme IDer pr. bruger ville også være fin, da vi ofte sender screenshots frem og tilbage m. opgaver der skal granskes nærmere. Så snart opgaverne er kørt gennem i "altid forkerte" og ryger i "blandende" kan de godt være svære at luge frem igen. Evt. en liste på profilen hvor der kan startes en seperat quiz m. gemte spørgsmål. :)

**Comment by thomasjensen1194** [comment]
At man kan gemme spørgsmål, dele quiz og hente spørgsmål baseret på ID er planlagt. Men vi har en stor omvæltning af vores database der skal køre først, derefter kommer det. Så engang efter sommerferien, er de features du anmoder om, der nok.

**Comment by thomasjensen1194** [comment]
En eventuel hurtig løsning er, at ID bliver vist på hvert spørgsmål, og at man så kan skrive ID’et i søgefeltet for at komme tilbage til det spørgsmål. Tænker du at det er en okay middelvej?

**Comment by thomasjensen1194** [comment]
https://github.com/morsby/medmcq/issues/291

**Comment by thomasjensen1194** [comment]
Jeg har implementeret den manuelle funktion på siden nu, så man selv kan vinge af, hvad man vil: 457e4c0c7d74fd01963bc9bea37fbffe551f356d

**Comment by ALangeland** [comment]
Super god og hurtig implementering. 
Jeg har endnu et forslag, da det lader til i har et absurb overskud i eksamensperioden. 
- Sortering af test i "Blandede opgaver med lavest korrekt svar procent først", da de ofte hober sig op. Jeg har ihvertfald selv over 300 :)

**Comment by thomasjensen1194** [comment]
Nogle ting er nemmere at implementere end andre, men jeg vil se hvad jeg kan gøre.

**Comment by thomasjensen1194** [comment]
Du kan nu sortere efter alle felter på profilsiden: 3c31a37c78a07297994d1114249f8090f4e9b7c0
