### ISSUE TITLE
Tag-dropdown er ustabil 

### ISSUE THREAD

**Issue by morsby** [morsby/medmcq#297]
Dropdown-menuen for tags er ustabil - nogle gange åbner undermenuen ikke op (men viser bare en tynd streg), eller hele dropdownen lukker.

(ellers skide god menu med undermenuer!)

**Comment by thomasjensen1194** [comment]
Ja jeg ved det, men det er semantics’ bug. Har lavet en issue hos dem, men vi kan godt finde en alternativ pakke der er mere stabil.

**Comment by thomasjensen1194** [comment]
Det med at den lukker er koblet til om man trykker på teksten eller bare på “boksen”. Hvis man ikke trykker direkte på teksten, åbner undermenuen ikke - det er ikke godt lavet af dem

**Comment by thomasjensen1194** [comment]
https://github.com/Semantic-Org/Semantic-UI-React/issues/3637
