### ISSUE TITLE
Nyrer skal fjernes som tag

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#313]
Det kan gives til næsten alle urologiske spørgsmål, der omhandler øvre problemer. Spørgsmål som bærer tagget kan sagtens indgå under bedre tags.
Afventer SQL, da det er nemmere at fjerne tags her.

**Comment by morsby** [comment]
Hvad gør du, når du sletter et tag? Har du givet spørgsmålene nye tags? For ellers mister vi jo inddelingen.

**Comment by thomasjensen1194** [comment]
Jeg har ikke fjernet tags?
