### ISSUE TITLE
Tagging af samme spørgsmål samtidig, lader dig tagge samme tag 2 gange.

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#321]
Meget sjælden case, men skal alligevel blokeres på backend.

**Comment by morsby** [comment]
Er det det her, du mener?

![image](https://user-images.githubusercontent.com/10538218/59159556-a1db2a80-8acb-11e9-8ead-57eb91f8069f.png)

**Comment by thomasjensen1194** [comment]
Ja, routen skal lige kunne håndtere votes på duplicates (eventuelt skal de eksisterende bare upvotes). Måske vote routen og oprettelsen af nyt tag skal skrives sammen - det vil nok gøre det nemmere.

**Comment by thomasjensen1194** [comment]
Er det her fikset @morsby?

**Comment by morsby** [comment]
Jep, jep, det burde det være.
