### ISSUE TITLE
Ændring af format af svar/korrekte svar

### ISSUE THREAD

**Issue by morsby** [morsby/medmcq#382]
I stedet for at have
```js
question {
    ...
    answer1: 'Bla',
    answer2: 'De',
    answer3: 'Blaa',
    correctAnswers: [1, 2]
}
```

ville det nok være mere elegant (særligt med GraphQL) at have:

```js
question {
    ...
    answers: [
        { id: 1,
          text: 'Bla',
          correct: true },
        { id: 2,
          text: 'De',
          correct: true },
        { id: 3,
          text: 'Blaa',
          correct: false }
    ]
}
```

Man vil undgå en del hacky løsninger i resolvers, og at tjekke, om brugeren svarer rigtigt, vil nok også blive mere elegant.

Til gengæld vil migrering af brugeres svar være rimeligt bøvlet - så det er et projekt til fremtiden.

**Comment by thjendk** [comment]
Hermed done https://github.com/thjendk/medmcq/pull/9
