### ISSUE TITLE
App virker ikke i internet explorer

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#401]
Smider følgende fejl:
![image](https://user-images.githubusercontent.com/44089656/66604694-f512d600-ebae-11e9-832e-1b2f7429ebe8.png)

**Comment by thomasjensen1194** [comment]
ApolloClient er ikke understøttet af internet explorer (men på den anden side burde ingen bruge den forældede browser)

**Comment by morsby** [comment]
Fint med mig. Kan vi evt. lave et tjek i index.html for browser? Og klage hvis det er IE?

**Comment by morsby** [comment]
Bare så folk får et løsningsforslag.

**Comment by thomasjensen1194** [comment]
Jep, muligvis kan følgende kode (i Update 1) inkluderes: https://stackoverflow.com/a/22551342/10529916

**Comment by thomasjensen1194** [comment]
Integreret i e588c87412a906cf53fa2735ce2c73252131032c
