### ISSUE TITLE
Spørgsmål til eksamenssæt E2019 7. semester mht. procenterne

### ISSUE THREAD

**Issue by 202088** [morsby/medmcq#441]
1. spørgsmål i E2019 7.sem, er det rigtige svar det grønne (Mistanke om pancreascancer - 14%), men "Mistanke om benign sygdom i lever- og galdeveje" som er rød, får hele 57%.

Forstår ikke helt hvorfor, er ny i systemet, så jeg blev lidt forvirret.
Skal jeg se bort fra procenterne, og bare vide at det korrekte svar til eksamen, er det der markeres grønt.?

**Comment by thomasjensen1194** [comment]
Hvis du fører musen over procenten, står der en forklaring på hvad det betyder. At procenten er højere for det forkerte svar, betyder blot at mange svarer forkert på den opgave. Det er den procentdel af studerende, der ved deres første forsøg, har valgt den valgmulighed.

**Comment by 202088** [comment]
Okey, mange tak for svaret. Så det er rigtig forstået, at det grønne er det helt korrekte?

**Comment by thomasjensen1194** [comment]
Det grønne er altid det korrekte svar :-) Procenterne er baseret på brugere af systemet (som dig).
