### ISSUE TITLE
Der er problemer op medmcq med at loade siden 

### ISSUE THREAD

**Issue by Nataliemed** [morsby/medmcq#446]
Jeg oplever i øjeblikket at siden ikke vil loade så kan ikke komme til at vælge semester eller starte MCQ.

**Comment by thjendk** [comment]
Der er i øjeblikket et planlagt service vindue på alle AU’s systemer, hvorved det ikke vil fungere. Hvis du stadig oplever fejlen på mandag, så skriv igen :-)

**Comment by thjendk** [comment]
Arbejdet er nu overstået, og der skulle gerne være hul igennem. Hvis det stadig ikke virker for dig, så svar venligst igen med et screenshot af din dev-console. Du kan finde denne ved at følge følgende guide for din browser: https://kb.mailster.co/how-can-i-open-the-browsers-console/ (2 små skridt). Tag derefter et screenshot af hvad end der står, og indsæt det her 😊
