### ISSUE TITLE
Tags bør følge sygdomslisten? 

### ISSUE THREAD

**Issue by morsby** [morsby/medmcq#59]
Bør vi bare definere tags ud fra sygdomslisten? Det  ville være ret nemt at komme i gang med, og det er vel også værdifuldt at kunne se sin præstation ifht. sygdomslisten.

**Comment by thomasjensen1194** [comment]
Mener du at hver sygdom skal have et tag? Pneumoni, cystit, meningit? Skal der så også være symptomer med? Ascites, ondt i maven, LUTS osv?

**Comment by morsby** [comment]
Jaaaa, jeg ved det ikke helt. Det bliver mange - og vil ofte give svaret på spørgsmålet.

Evt. gruppere det lidt ud fra symptomkomplekser eller noget.. Eller måske bare køre full-on ud fra sygdomsliste. Jeg kan ikke helt beslutte mig.

**Comment by thomasjensen1194** [comment]
Jeg kunne godt tænke mig i sommerferien at lære python, og køre noget machine learning på spørgsmålene. På den måde identificere hyppigt brugte ord i spørgsmålene, og gruppere dem efter de hyppigt brugte ord. Det kunne være en spændende opgave, og jeg tænker og håber på at det vil komme til at ligne sygdomslisten ret godt.

**Comment by morsby** [comment]
Nu har jeg set en del på tags på 8. og 9. - sygdomslisten/overskrifter fra bogen er en ret god måde at komme omkring det på, så man ikke glemmer specialer.

Så det er jeg egentlig rimelig stor fan af. 

Ikke at det udelukker dit machine learning. ;-)

**Comment by thomasjensen1194** [comment]
Vi lukker denne for nu. Det kører super med brugerne selv laver tags, og det kan ikke på nogen måde blive bedre på blot 1000 spørgsmål med machine learning (hvor hvert specifikt emne måske kun indeholder 4-5 spørgsmål). Prediction af nye spørgsmål's emne er altså usandsynligt med machine learning, da vi ikke har nok "training" data. Men sjovt kunne det have været!
