### ISSUE TITLE
Vi bør måske kunne sætte en besked som fremgår under rapporteringen - sådan at vi ikke får duplikerede rapports hele tiden

### ISSUE THREAD

**Issue by thomasjensen1194** [morsby/medmcq#68]
Altså at vi kan sætte bestemte beskeder for hvert spørgsmål, hvis der har været en rapport tidligere. Eller udtænke en måde, hvorpå vi kan tracke rapporteringer til spørgsmålet, og vise svaret, sådan at det samme ikke bliver rapporteret igen. Det er nok de færreste som kigger github igennem.

**Comment by morsby** [comment]
Evt. kan vi udnytte det her: https://developer.github.com/v3/issues/#create-an-issue

**Comment by morsby** [comment]
... Eller måske snarere hente listen via get. Post kræver vist en bruger (så det giver ikke meget ifht) fire.

**Comment by thomasjensen1194** [comment]
Tilføjet i tidligere commit
